name: Run checks

on:
    pull_request:
        types: [ready_for_review]
        branches:
            - main
            - master
            - dev

jobs:
    lint:
        name: Lint
        runs-on: blacksmith-4vcpu-ubuntu-2404
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: useblacksmith/setup-node@v5
              with:
                  node-version: 20
              
            - name: Install client dependencies
              working-directory: client
              run: npm i

            - name: Run client lint
              working-directory: client
              run: npm run lint

            - name: Install server dependencies
              working-directory: server
              run: npm i

            - name: Run server lint
              working-directory: server
              run: npm run lint
            
    typecheck:
        name: Typecheck
        runs-on: blacksmith-4vcpu-ubuntu-2404
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Node.js
              uses: useblacksmith/setup-node@v5
              with:
                  node-version: 20
            - name: Install client dependencies
              working-directory: client
              run: npm i

            - name: Run client typecheck
              working-directory: client
              run: npm run typecheck

            - name: Install server dependencies
              working-directory: server
              run: npm i

            - name: Run server typecheck
              working-directory: server
              run: npm run typecheck


    # check-migrations:
    #     name: Check Migrations
    #     runs-on: blacksmith-4vcpu-ubuntu-2404
    #     steps:
    #         - name: Checkout code
    #           uses: actions/checkout@v4
    #         - name: Setup Node.js
    #           uses: useblacksmith/setup-node@v5
    #           with:
    #               node-version: 20
    #         - name: Install dependencies
    #           run: npm i
    #         - name: Generate migrations
    #           run: npm db:generate
    #         - name: Check if migrations are up to date
    #           run: |
    #               if [ -z "$(git status --porcelain)" ]; then
    #                   echo "Migrations are up to date"
    #                   exit 0
    #               else
    #                   echo "Migrations are not up to date"
    #                   exit 1
    #               fi